### ISSUE TITLE
ErrorMessage": "Message: no such element: Unable to locate element: 

### ISSUE THREAD

**Issue by shihabemd** [CasCard/AutoCDSL#4]
Thanks for making the automation of CDSL authorisation. However I'm getting below error in xpath finding Authorisation. Could you please help me to resolve this issue ?

{
  "errorMessage": "Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//a[text()='Authorisation']\"}\n  (Session info: headless chrome=69.0.3497.81)\n  (Driver info: chromedriver=2.43.600233 (523efee95e3d68b8719b3a1c83051aa63aa6b10d),platform=Linux 4.14.255-285-225.501.amzn2.x86_64 x86_64)\n",
  "errorType": "NoSuchElementException",
  "stackTrace": [
    "  File \"/var/task/lambda_function.py\", line 155, in lambda_handler\n    driver.find_element_by_xpath(\"//a[text()='Authorisation']\").click()\n",
    "  File \"/opt/python/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py\", line 394, in find_element_by_xpath\n    return self.find_element(by=By.XPATH, value=xpath)\n",
    "  File \"/opt/python/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py\", line 978, in find_element\n    'value': value})['value']\n",
    "  File \"/opt/python/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n",
    "  File \"/opt/python/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"
  ]
}

**Comment by CasCard** [comment]
There can be two reasons this can occur :

1. You don't have any stocks in your Demat account, because of this there won't be any Authorisation link under the holdings tab of the kite.
2. Your 2 Factor Authentication (2FA) secret key is incorrect. Try regenerating and place under KITE_SECRET section on environmental variables.

Follow the instructions [here](https://abelcheruvathoor.gitbook.io/) . While going through Step 3 you should parallelly setup Step 4 as well as 2FA authentication key has to be entered in the AWS Lambda as well.
